version: '3.7'

services:
  mukef-apis:
    container_name: server
    build: ./
    command: npm start
    working_dir: /user/src/app
    ports:
      - "6000:6000"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$mongodb_user
      - DB_PASSWORD=$mongodb_password
      - MONGODB_DATABASE=$mongodb_database
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    networks:
      - mukef
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$mongodb_user
      - MONGO_INITDB_ROOT_PASSWORD=$mongodb_password

    volumes:
      - db:/data/db
    
volumes:
  db:

networks:
  mukef:
    driver: bridge